apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  namespace: default
spec:
  builder:
    command: build
    container:
      name: ''
      resources: {}
  imagepullsecret: ''
  keeparchive: false
  poolsize: 4
  resources: {}
  runtime:
    container:
      name: ''
      resources: {}
  version: 2
