apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  namespace: default
spec:
  invokeStrategy:
    executionStrategy:
      executorType: poolmgr
      maxScale: 1
      minScale: 1
      specializationTimeout: 120
      targetCPUPercent: 0
    strategyType: execution
  concurrency: 500
  environment:
    namespace: default
  functionTimeout: 60
  idletimeout: 60
  package:
    packageref:
      namespace: default
  requestsPerPod: 1
  resources: {}
