apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
spec:
  createingress: false
  functionref:
    functionweights: {}
    type: name
  host: ''
  ingressconfig:
    annotations: {}
    host: '*'
    tls: ''
  method: ''
  methods: [GET]
  prefix: ''
