apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: $name
  namespace: $functionNamespace
  labels: $labels
  annotations: $annotations
spec:
  invokeStrategy:
    executionStrategy:
      executorType: $executorType
      maxScale: $maximumScale
      minScale: $minimumScale
      specializationTimeout: $specializationTimeout
      targetCPUPercent: $targetCPUPercent
    strategyType: execution
  concurrency: $concurrency
  environment:
    name: $environment
    namespace: $environmentNamespace
  functionTimeout: $functionTimeout
  idletimeout: $idleTimeout
  package:
    functionName: $handler
    packageref:
      name: $packageName
      namespace: $packageNamespace
  requestsPerPod: $requestsPerPod
  resources: {}
  configmaps: $configMaps
  secrets: $secrets
