apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: $name
  namespace: $fnNamespace
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: $executortype
      MaxScale: $maxscale
      MinScale: $minscale
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: $concurrency
  environment:
    name: $environment
    namespace: $envNamespace
  functionTimeout: $timeout
  idletimeout: $idletimeout
  package:
    functionName: $handler
    packageref:
      name: $packageName
      namespace: $packageNamespace
  requestsPerPod: $requestsperpod
  resources: {}
