apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: $name
  namespace: $functionNamespace
spec:
  createingress: false
  functionref:
    functionweights: {}
    name: $functionName
    type: name
  host: ''
  ingressconfig:
    annotations: {}
    host: '*'
    path: $url
    tls: ''
  method: ''
  methods: $methods
  prefix: $prefix
  relativeurl: $url
